groups:
- name: scylla.rules
  rules:
  - record: all_scheduling_group
    expr: sum by (cluster, scheduling_group_name) (scylla_storage_proxy_coordinator_write_latency_count + scylla_storage_proxy_coordinator_read_latency_count) > 0

