# config file version
apiVersion: 1
datasources:
- name: scylla-datasource
  type: scylladb-scylla-datasource
  orgId: 1
  isDefault:
  jsonData:
    host: ''
  secureJsonData:
    user: 'SCYLLA_USER'
    password: 'SCYLLA_PSSWD'
